from ..prompts.templates import EXPLOIT_PROMPT

EXPLOIT_CONFIGS: dict[str, dict] = {
    "sqli": {
        "vuln_type": "sqli",
        "rag_filter": "sqli",
        "tools_hint": ["sqlmap", "curl"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "xss": {
        "vuln_type": "xss",
        "rag_filter": "xss",
        "tools_hint": ["dalfox", "xsser", "curl"],
        "max_iterations": 22,
        "prompt": EXPLOIT_PROMPT,
    },
    "lfi": {
        "vuln_type": "lfi",
        "rag_filter": "lfi",
        "tools_hint": ["curl", "ffuf"],
        "max_iterations": 18,
        "prompt": EXPLOIT_PROMPT,
    },
    "rfi": {
        "vuln_type": "rfi",
        "rag_filter": "lfi",
        "tools_hint": ["curl"],
        "max_iterations": 16,
        "prompt": EXPLOIT_PROMPT,
    },
    "ssrf": {
        "vuln_type": "ssrf",
        "rag_filter": "ssrf",
        "tools_hint": ["curl", "interactsh"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "command_injection": {
        "vuln_type": "command_injection",
        "rag_filter": "command_injection",
        "tools_hint": ["commix", "curl"],
        "max_iterations": 18,
        "prompt": EXPLOIT_PROMPT,
    },
    "csrf": {
        "vuln_type": "csrf",
        "rag_filter": "csrf",
        "tools_hint": ["curl"],
        "max_iterations": 18,
        "prompt": EXPLOIT_PROMPT,
    },
    "file_upload": {
        "vuln_type": "file_upload",
        "rag_filter": "file_upload",
        "tools_hint": ["curl"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "brute_force": {
        "vuln_type": "brute_force",
        "rag_filter": "brute_force",
        "tools_hint": ["hydra", "curl"],
        "max_iterations": 18,
        "prompt": EXPLOIT_PROMPT,
    },
    "ssti": {
        "vuln_type": "ssti",
        "rag_filter": "ssti",
        "tools_hint": ["curl"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "xxe": {
        "vuln_type": "xxe",
        "rag_filter": "xxe",
        "tools_hint": ["curl"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "idor": {
        "vuln_type": "idor",
        "rag_filter": "broken_access_control",
        "tools_hint": ["curl", "ffuf"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "open_redirect": {
        "vuln_type": "open_redirect",
        "rag_filter": "other",
        "tools_hint": ["curl"],
        "max_iterations": 15,
        "prompt": EXPLOIT_PROMPT,
    },
    "insecure_deserialization": {
        "vuln_type": "insecure_deserialization",
        "rag_filter": "insecure_deserialization",
        "tools_hint": ["curl"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "authentication_bypass": {
        "vuln_type": "authentication_bypass",
        "rag_filter": "authentication_bypass",
        "tools_hint": ["curl", "hydra"],
        "max_iterations": 20,
        "prompt": EXPLOIT_PROMPT,
    },
    "misconfiguration": {
        "vuln_type": "misconfiguration",
        "rag_filter": "security_misconfiguration",
        "tools_hint": ["nikto", "nuclei", "curl"],
        "max_iterations": 15,
        "prompt": EXPLOIT_PROMPT,
    },
}
